name: Build and Deploy nvrx-rk3588....

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This will use your self-hosted runner
    env:  # Environment variables for the entire job
      GIT_HOME_DIR: "/home/neeldharsandiya/neel/selfhostedrunners/actions-runner/ndworkspace"
  
    steps:
      - name: Preparing Environment
        run: |
          echo "Set/Export necessary variables..."
          echo "CURRENT_GITHUB_REPOSITORY=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
          sleep 5
          
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: matrix-comsec-pvt-ltd/ipvs-nvr-app
          submodules: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
    
      - name: Download build dependencies from JFrog
        run: |          
          sleep 3
          echo "Downloading Dependencies..."
          #curl -C - -L --fail -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_API_KEY }} -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/Device_Client_Setup_8.7.52.exe" "http://192.168.27.92:8082/artifactory/ipvs-nvr-device-client-prod-release/productionbuild/8.7.52/Device_Client_Setup_8.7.52.exe"
          curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_API_KEY }} -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/Device_Client_Setup_8.7.52.exe" "http://192.168.27.92:8082/artifactory/ipvs-nvr-device-client-prod-release/productionbuild/8.7.52/Device_Client_Setup_8.7.52.exe"
          if [ $? -ne 0 ]; then
              echo "Download failed. Retrying..."
          fi
          #sleep 3
          #curl -C - -L --fail -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASSWORD }} -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/platform_upgrade.zip" "http://192.168.27.92:8082/artifactory/ipvs-nvrx-platform-prod-release/productionbuild/8.7.0/rk3588/target/platform_upgrade.zip"
          #if [ $? -ne 0 ]; then
          #    echo "Download failed. Retrying..."
          #fi
          #sleep 3
          #curl -C - -L --fail -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASSWORD }} -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/host.tar.xz" "http://192.168.27.92:8082/artifactory/ipvs-nvrx-platform-prod-release/productionbuild/8.7.0/rk3588/host/host.tar.xz"
          #if [ $? -ne 0 ]; then
          #    echo "Download failed. Retrying..."
          #fi
          sleep 3

      - name: Compile and Prepare Package
        run: |
          echo "Change directory & apply Make command"
          echo "Path: $GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY"
          cd "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY" && ls -al && make BOARD_TYPE=RK3588_NVRH RELEASE_TYPE=QA PASSWORD='neel' release
          sleep 5

      - name: Upload release artifacts to JFrog
        run: |
          echo "Uploading Artifacts..."
          cd "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build"
          curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASSWORD }} -T "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/NVR_RK3588H-2.2.0.zip" "http://192.168.27.92:8082/artifactory/ipvs-nvrx-prod-release/productionbuild/2.2.0/rk3588/NVR_RK3588H-2.2.0.zip"
          
          
          
