name: Build and Deploy nvr_rk3588..

on:
  push:
    branches:
      - xyz

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: Install Build Essentials
        run: |
          sudo apt-get update
          #sudo apt-get install -y build-essential

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: matrix-comsec-pvt-ltd/ipvs-nvr-app
          submodules: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Display Environment
        run: |
          echo "Current Directory is :"
          pwd
          
          echo "Cloned repository is :"
          ls -la  # List files in the repository
          
