name: Build and Deploy nvr_rk3588..

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SECRET_TOKEN: ${{ secrets.YOUR_ORG_SECRET }}
  
    steps:
      - name: Install Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: matrix-comsec-pvt-ltd/ipvs-nvr-rk3588-app
          submodules: true
          #token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Display files
        run: |
          echo "Cloned repository:"
          ls -la  # List files in the repository
