name: Build and Deploy nvr_rk3588.......

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This will use your self-hosted runner
  
    steps:
      - name: Install Build Essentials
        run: |
          sudo apt-get update
      
      - name: Preparing Environment
        run: |
          echo "Export necessary variables..."
          current_github_repository=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "current_github_repository = $current_github_repository"
          
          export GIT_HOME_DIR=/home/neeldharsandiya/neel/selfhostedrunners/actions-runner/ndworkspace/$current_github_repository
          echo "GIT_HOME_DIR = $GIT_HOME_DIR"  # Make sure the variable is correctly exported
          
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: matrix-comsec-pvt-ltd/ipvs-nvr-app
          submodules: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
    
      - name: Download build dependencies from JFrog
        run: |
          echo "Downloading Dependencies..."
          curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_API_KEY }} -o "$GIT_HOME_DIR/$current_github_repository/src/Application/Build/Device_Client_Setup_8.7.52.exe" "http://192.168.27.92:8082/artifactory/ipvs-nvr-device-client-prod-release/productionbuild/8.7.52/Device_Client_Setup_8.7.52.exe"
          #curl -u admin:AKCpBtNTD6yAkngV6hWDtMhyRgDWynmqF7oiwzp7caQ51fDvCZhKpPt5CPkBDwc8WvTGZ33qA -o $GIT_HOME_DIR/$current_github_repository/src/Application/Build/Device_Client_Setup_8.7.52.exe http://192.168.27.92:8082/artifactory/ipvs-nvr-device-client-prod-release/productionbuild/8.7.52/Device_Client_Setup_8.7.52.exe
          #curl -u admin:Neel@2822 -o $GIT_HOME_DIR/$current_github_repository/src/Application/Build/platform_upgrade.zip http://192.168.27.92:8082/artifactory/ipvs-nvrx-platform-prod-release/productionbuild/8.7.0/rk3588/target/platform_upgrade.zip
          #curl -u admin:Neel@2822 -o $GIT_HOME_DIR/$current_github_repository/src/Application/Build/host.tar.xz http://192.168.27.92:8082/artifactory/ipvs-nvrx-platform-prod-release/productionbuild/8.7.0/rk3588/host/host.tar.xz

          echo "Check Downloads..."
          cd "$GIT_HOME_DIR/$current_github_repository/src/Application/Build" && ls -al
          
          
          
