name: Build and Deploy nvr_rk3588

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: matrix-comsec-pvt-ltd/ipvs-nvr-rk3588-app
          submodules: true  # Clone submodules as well 
